# Generated by Django 5.2 on 2025-05-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='price_monthly',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price_yearly',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
