# Generated by Django 5.2 on 2025-05-27 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0003_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('default_label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TariffFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly')], max_length=10)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariffs.feature')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariffs.tariff')),
            ],
            options={
                'unique_together': {('tariff', 'feature', 'period')},
            },
        ),
        migrations.AddField(
            model_name='tariff',
            name='features',
            field=models.ManyToManyField(through='tariffs.TariffFeature', to='tariffs.feature'),
        ),
    ]
