# Generated by Django 5.2 on 2025-05-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0005_paymentdetail_paymenthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarifffeature',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='tarifffeature',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
