# Generated by Django 5.2 on 2025-05-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('google', 'Google')], default='normal', max_length=10),
        ),
    ]
