name: React Build and Deploy with Yarn

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.AZMO_SERVER_SSH_KEY }}" | base64 --decode > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
        env:
            AZMO_SERVER_SSH_KEY: ${{ secrets.AZMO_SERVER_SSH_KEY }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "23.9.0"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies with Yarn
        run: yarn install

      - name: Build the project
        run: yarn build

      - name: Install rsync
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync

      - name: Upload files via SFTP
        run: |
            echo "Uploading files via rsync..."
            rsync -avz -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.AZMO_SERVER_PORT }}" build/ "${{ secrets.AZMO_SERVER_USERNAME }}@${{ secrets.AZMO_SERVER_HOST }}:${{ secrets.AZMO_SERVER_PATH }}"
        env:
            AZMO_SERVER_USERNAME: ${{ secrets.AZMO_SERVER_USERNAME }}
            AZMO_SERVER_HOST: ${{ secrets.AZMO_SERVER_HOST }}
            AZMO_SERVER_PATH: ${{ secrets.AZMO_SERVER_PATH }}
            AZMO_SERVER_PORT: ${{ secrets.AZMO_SERVER_PORT }}
