name: React Build and Deploy with Yarn

on:
    push:
        branches:
            - dev

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up SSH key
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 --decode > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "23.9.0"

            - name: Install Yarn
              run: npm install -g yarn

            - name: Install dependencies with Yarn
              run: yarn install

            - name: Build the project
              run: yarn build

            - name: Install rsync
              run: |
                  apt-get update
                  apt-get install -y rsync

            - name: Upload files via SFTP
              run: |
                  echo "Uploading files via rsync..."
                  # Используем rsync для синхронизации файлов
                  rsync -avz -e "ssh -o StrictHostKeyChecking=no" build/ "${{ secrets.SFTP_USER }}@${{ secrets.SFTP_HOST }}:public_html"
              env:
                  SFTP_USER: ${{ secrets.SFTP_USER }}
                  SFTP_HOST: ${{ secrets.SFTP_HOST }}
